# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestApplication' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestApplication
  pod 'Alamofire', '~> 4.0'
  pod 'ObjectMapper', '~> 2.2'
  pod 'PromiseKit', '~> 4.0'
  pod 'Charts', '3.0.3'
  
end
